spring.application.name=backend
spring.datasource.url=jdbc:postgresql://postgres:5432/fitschedule
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
